Models/Client.cs
using System;
using System.ComponentModel.DataAnnotations;
using MvcClients.Attributes;

namespace MvcClients.Models
{
	public class Client
	{
		[Key]
		public int ClientId { get; set; }

		[Display(Name="Civilité")]
		public string Civilite  { get; set; }

		[Required(ErrorMessage = "Le champ 'Nom' est requis")]
		public string Nom { get; set; }

		[Required(ErrorMessage = "Le champ 'Prénom' est requis")]
		[Display(Name = "Prénom")]
		public string Prenom { get; set; }

		[Required(ErrorMessage = "Le champ 'Date de naissance' est requis")]
		[Display(Name = "Date de naissance")]
		[DataType(DataType.Date), BirthDate(MinimumAge = 18)]
		public DateTime DateNaissance { get; set; }

		[Required(ErrorMessage = "Le champ 'Code Postal' est requis")]
		[Display(Name = "Code Postal")]
		[DataType(DataType.PostalCode)]
		public int CodePostale { get; set; }

		public string Adresse { get; set; }
		
		[Required(ErrorMessage = "Le champ 'Pays' est requis")]
		public string Pays { get; set; }

		[Display(Name = "Mail")]
		[DataType(DataType.EmailAddress)]
		[EmailAddress(ErrorMessage = "Adresse mail non valide (ex: jean@exemple.fr)")]
		public string Mail { get; set; }

		[Required(ErrorMessage = "Le champ 'Téléphone' est requis")]
		[Display(Name = "Téléphone"), PhoneNumber]
		public string Telephone { get; set; }

		[Required(ErrorMessage = "Le champ 'Ville' est requis")]
		[Display(Name="Ville/Commune")]
		public string Ville { get; set; }
	}
}

Models/ErrorViewModel.cs
using System;

namespace MvcClients.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/SeedData.cs
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using MvcClients.Data;

namespace MvcClients.Models
{
	public class SeedData
	{
		public static void Initialize(IServiceProvider serviceProvider)
		{
			using (var context = new MvcClientsContext(
				serviceProvider.GetRequiredService<
					DbContextOptions<MvcClientsContext>>()))
			{
				if (context.Client.Any())
				{
					return; //DB déjà rempli
				}

				context.Client.AddRange(
					new Client
					{
						Civilite = "Mr",
						Nom = "Dujardin",
						Prenom = "Jean",
						DateNaissance = new DateTime(1972, 06, 19),
						Adresse = "4 rue de la bastille",
						CodePostale = 75000,
						Ville = "Paris",
						Pays = "France",
						Mail = "jean.dujardin@live.fr",
						Telephone = "0612345678"
					},
					new Client
					{
						Civilite = "Mme",
						Nom = "Lamy",
						Prenom = "Alexandra",
						DateNaissance = new DateTime(1971, 10, 14),
						Adresse = "4 avenue Jean Jaures",
						CodePostale = 78000,
						Ville = "Versailles",
						Pays = "France",
						Mail = "lamy.alx@gmail.com",
						Telephone = "0612345678"
					}
				);
				context.SaveChanges();
			}
		}
	}
}

Controllers/ClientsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcClients.Data;
using MvcClients.Models;

namespace MvcClients.Controllers
{
    public class ClientsController : Controller
    {
        private readonly MvcClientsContext _context;

        public ClientsController(MvcClientsContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Client.ToListAsync());
        }   

        public async Task<IActionResult> GetAll()
		{
            var list = await _context.Client.ToListAsync();
            return Json(new { data = list });
		}

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.ClientId == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Civilite,Nom,Prenom,DateNaissance,CodePostale,Adresse,Pays,Mail,Telephone,Ville")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        public async Task<IActionResult> Create5User()
		{
            Client client;
            for(int i=0; i < 5; i++)
			{
                client = new Client();
                client.Civilite = "Mr";
                client.Nom = "New"+i;
                client.Prenom = "Client"+i;
                client.DateNaissance = new DateTime(2011, 6, 10);
                client.CodePostale = 76600;
                client.Adresse = "New Address" + i;
                client.Pays = "Pays" + i;
                client.Mail = "mail@gmail.com";
                client.Telephone = "0612345678";
                client.Ville = "New Ville" + i;

                //Ajout dans la BDD
                _context.Add(client);
                //Commit et push les changements sur la BDD 
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
		}

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Civilite,Nom,Prenom,DateNaissance,CodePostale,Adresse,Pays,Mail,Telephone,Ville")] Client client)
        {
            if (id != client.ClientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.ClientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstAsync(m => m.ClientId == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Client.FindAsync(id);
            _context.Client.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Client.Any(e => e.ClientId == id);
        }
    }
}

Controllers/ProcedureController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcClients.Controllers
{
	public class ProcedureController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult RJ45()
		{
			return View();
		}

		public IActionResult CPL()
		{
			return View();
		}

		public IActionResult Wifi()
		{
			return View();
		}

	}
}

Views/Clients/Create.cshtml
@model MvcClients.Models.Client

@{
    ViewData["Title"] = "Nouveau";
}

<h1>Nouveau</h1>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Civilite" class="control-label"></label>
                <select asp-for="Civilite" class="form-control">
                    <option value="Mr">Monsieur</option>
                    <option value="Mme">Madame</option>
                </select>
                <span asp-validation-for="Civilite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNaissance" class="control-label"></label>
                <input asp-for="DateNaissance" class="form-control" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodePostale" class="control-label"></label>
                <input asp-for="CodePostale" class="form-control" />
                <span asp-validation-for="CodePostale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ville" class="control-label"></label>
                <input asp-for="Ville" class="form-control" />
                <span asp-validation-for="Ville" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pays" class="control-label"></label>
                <input asp-for="Pays" class="form-control" />
                <span asp-validation-for="Pays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ajouter" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clients/Delete.cshtml
@model MvcClients.Models.Client

@{
    ViewData["Title"] = "Supprimer";
}

<h1>Suppression</h1>


<div>
    <h4>Client à supprimer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Civilite)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Civilite)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CodePostale)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CodePostale)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ville)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ville)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pays)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pays)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClientId" />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste</a>
    </form>
</div>

Views/Clients/Details.cshtml
@model MvcClients.Models.Client

@{
    ViewData["Title"] = "Détails";
}

<h1>Fiche Client</h1>

<div>
    
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Civilite)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Civilite)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CodePostale)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CodePostale)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ville)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ville)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pays)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pays)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ClientId">Modifier</a> |
    <a asp-action="Index">Retour à la liste</a>
</div>

Views/Clients/Edit.cshtml
@model MvcClients.Models.Client

@{
    ViewData["Title"] = "Modifier";
}

<h1>Modification</h1>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ClientId" />
            <div class="form-group">
                <label asp-for="Civilite" class="control-label"></label>
                <select asp-for="Civilite" class="form-control">
                    <option value="Mr">Monsieur</option>
                    <option value="Mme">Madame</option>
                </select>
                <span asp-validation-for="Civilite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNaissance" class="control-label"></label>
                <input asp-for="DateNaissance" class="form-control" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodePostale" class="control-label"></label>
                <input asp-for="CodePostale" class="form-control" />
                <span asp-validation-for="CodePostale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ville" class="control-label"></label>
                <input asp-for="Ville" class="form-control" />
                <span asp-validation-for="Ville" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pays" class="control-label"></label>
                <input asp-for="Pays" class="form-control" />
                <span asp-validation-for="Pays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clients/Index.cshtml
@model IEnumerable<MvcClients.Models.Client>

@{
    ViewData["Title"] = "Index";
}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js"></script>

<h1>Mes clients</h1>

<table class="table table-striped" id="tblData">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Civilite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telephone)
            </th>

        </tr>
    </thead>
    <tbody>
@foreach(var item in Model)
        {
        <tr>
            <td>@item.ClientId</td>
            <td>@item.Civilite</td>

            <td>@item.Nom</td>

            <td>@item.Prenom</td>

            <td>@item.Mail</td>

            <td>@item.Telephone</td>
        </tr>
        }
    </tbody>
</table>

<p>
    <a asp-action="Create">Nouveau client</a><br />
    <a asp-action="Create5User">Ajouter 5 clients </a>
</p>

<a asp-controller="Procedure" asp-action="Index">Procédures</a>

@*@section Scripts{
        <script src="~/js/clients.js"></script>
    }*@

@section Scripts{
    <script>
            $(document).ready(function () {
                $('#tblData').DataTable();
            });
    </script>
}

Views/Procedure/CPL.cshtml
@{
    ViewData["Title"] = "Connexion CPL";
}

<ul style="list-style:none;">
    <li>
        <div>
            <h3>Etape 1</h3>
            <p>
                Une fois l'écran câblé et configuré, il faut relier le DumboPass à la MCTRL via le câble HDMI-DVI fourni,
                ainsi qu'avec le câble USB avec lequel la MCTRL a été configurée.
            </p>
        </div>
    </li>
    <li>
        <h3>Etape 2</h3>
        <p>
            Il faut mettre le DumboPass en réseau. <br />
            Pour se faire, il faut mettre les boîtier CPL (brancher électriquement en direct sur une arrivé murale)
            en réseau via des câbles RJ45, un relié directement au modem ou routeur du client, l’autre relié au DumboPass,
            puis appareillez les deux boîtier CPL en appuyant sur le bouton pair de chaque boîtier
            (vous devez appuyer sur les deux boutons dans un intervalle de deux minutes au maximum).
            Ensuite, vous pouvez brancher électriquement le DumboPass avec le transformateur fourni.
        </p>
    </li>
    <li>
        <h3>Etape 3</h3>
        <p>
            Une fois l’écran et le DumboPass alimentés et allumés le DumboPass affichera à l’écran sa version.
            Il va interroger notre API pour vérifier que sa clé est légitime et acceptée par nous.
            Si un message rouge s’affiche à l’écran cela signifie que la clé n’est pas acceptée
            ou bien que le DumboPass n’arrive pas à remonter sur le réseau, sinon passez à l’Etape 5 directement.
        </p>
    </li>
    <li>
        <h3>Etape 4</h3>
        <p>
            Dans un premier il faut appeler SmartLight pour demander confirmation de la validation de la clé. <br />
            Si elle ne l’était pas encore, redémarrer le DumboPass. <br />
            Si elle l’était déjà, le problème se situe au niveau du réseau interne.
            Vérifier l’accès réseau à l’aide d’un ordinateur portable
            en désactivant le Wifi de ce dernier et en branchant le câble RJ45 du DumboPass dessus.
        </p>
    </li>
    <li>
        <h3>Etape5</h3>
        <ul style="list-style:none;">
            <li>
                <h5>Etape5_1</h5>
                <p>
                    Vérifiez que vous avez bien un accès au réseau : <br />
                    - si vous voyez ce logo en bas à droite de votre barre de tâche vous avez un accès réseau vous pouvez poursuivre la procédure. <br />
                    - si vous voyez ce logo en bas à droite de votre barre de tâche c’est que vous n’avez pas d’accès réseau et donc que la prise ethernet
                    sur laquelle vous êtes branché n’est pas relier à un routeur ou à une boxe il faut informer le client
                    pour qu’il fasse le nécessaire ou utilisé les prises CPL.
                </p>
            </li>
            <li>
                <h5>Etape5_2</h5>
                <p>
                    Ensuite, vérifier que vous êtes autorisé à utiliser ce réseau. <br />
                    Pour ce faire, aller dans le menu démarrer de l’ordinateur (sous Windows), dans la barre de recherche taper cmd et lancez ce dernier
                </p>
            </li>
            <li>
                <h5>Etape5_3</h5>
                <p>
                    Une fois ouvert tapez la commande ipconfig<br />
                    Si vous voyez les champs Adresse IPv4 et Passerelle Par défaut rempli comme ci-dessus tester la connexion internet en accédant à google par exemple. <br />
                    Si en face de ces champs après les « : » il n’y a rien c’est que le réseau est en statique
                    il faut donc faire une demande d’adresse IP à la personne qui gère le réseau et ensuite utiliser l’application Android fournie pour configurer l’adresse statique du DumboPass.
                    Une fois l’adresse envoyée au DumboPass, veuillez le redémarrer et attendez qu’il s’initialise.
                </p>

            </li>
        </ul>
    </li>
    <li>
        <h3>Etape 6</h3>
        <p>
            À cette étape, le DumboPass devrait afficher un écran noir, ou lire un contenu s’il en possède.
            Le client n’a plus qu’à envoyer le contenu qu’il désire sur le DumboPass via l’application.
            Si ce n’est pas le cas et que le message rouge persiste, contacter SmartLight,
            il s’agit certainement d’une configuration réseau très particulière.
        </p>
    </li>
</ul>

<div>
    <a asp-action="Index">Retour</a>
</div>

Views/Procedure/Index.cshtml
@{
    ViewData["Title"] = "Procédures";
}

<h1>Procédure d'installation</h1>

<h3><a asp-controller="Procedure" asp-action="RJ45">CONNEXION VIA RJ45</a></h3>
<h3><a asp-controller="Procedure" asp-action="CPL">CONNEXION VIA CPL</a></h3>
<h3><a asp-controller="Procedure" asp-action="Wifi">CONNEXION VIA WIFI</a></h3>

<a asp-controller="Clients" asp-action="Index">Retour</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BDD Clients</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!--DataTable-->
    <link href="~/datatables/css/jquery.dataTables.css" rel="stylesheet" />
    <script src="~/datatables/js/jquery.dataTables.js"></script>

    <!--Vue JS-->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>
<body>
    <header>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--DataTable-->
    <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>